config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [ :index, :show, :new, :create ] do
    resources :doses, only: [ :new, :create ]
  end

  delete '/doses/:id', to: 'doses#destroy', as: 'dose'
  root 'cocktails#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show]

  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:create, :new]

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    @dose.ingredient = Ingredient.find(params[:dose][:ingredient]) unless params[:dose][:ingredient].blank?
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def dose_params
    params.require(:dose).permit(:description)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/index.html.erb
<h1>Our cocktails !</h1>

<div class="cards m-3">
<% @cocktails.each do |cocktail| %>

    <%= link_to cocktail_path(cocktail) do %>
    <div class="card-category " style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
           url('<%= cl_image_path cocktail.photo, height: 300, width: 400, crop: :fill %>')">
      <p> <%= cocktail.name %> </p>
    </div>
  <% end %>
<% end %>

</div>

app/views/cocktails/new.html.erb
<h1> Add a new cocktail ! </h1>

<%= simple_form_for [@cocktail] do |f| %>
  <%= f.input :name %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit "add a cocktail", class: "btn btn-primary" %>

<% end %>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name %></h1>
<%= cl_image_tag @cocktail.photo, height: 300, width: 400, crop: :fill %>


<ul>
  <% @cocktail.doses.each do |dose| %>
    <li style="list-style: none;"> <%= dose.description %> of <%= dose.ingredient.name %></li>
  <% end %>
</ul>

<%= link_to 'Back', cocktails_path %> |
<%= link_to 'Add a cocktail recipe', new_cocktail_dose_path(@cocktail) %>

app/views/doses/new.html.erb
<h1>New dose ! </h1>
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :ingredient, collection: Ingredient.order(:name), prompt: "Pick one from list" %>
  <%= f.input :description %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

<%= link_to 'or back', cocktail_path(@cocktail) %>

app/views/ingredients/index.html.erb
<h1>Our ingregients</h1>

<% @ingredients.each do |i| %>
  <h2><%= i.name %></h2>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
     <%= javascript_include_tag "application" %>
     <%= javascript_pack_tag "application" %>
  </head>

  <body>
     <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Home", cocktails_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "New cocktail", new_cocktail_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</div>


    <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://guardian.ng/wp-content/uploads/2018/06/Various-cocktails.-Photo-Getty-Images.jpg)">
        <h1 class="titre">L'apero du Wagon</h1>
    </div>



    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>